### ISSUE TITLE
Incompatible with Bobby

### ISSUE THREAD

**Issue by BapllStar** [KrLite/Tap-Tab#10]
Whenever using this mod along with [Bobby](https://modrinth.com/mod/bobby), the visuals of the hotbar doesn't update, when tabbing. Whenever placing a block after having cycled, the block which is displayed in your hotbar, briefly flashes in the spot, where you place the block. But then it turns into the block that is actually in your hotbar, but isn't displayed.

**Comment by KrLite** [comment]
I will check it.

**Comment by KrLite** [comment]
I believe there's almost nothing to do with **Bobby,** however, I found two issues here.

1. **It's possible that you are using an older version.**

The current code does have bugs, but won't cause any of the described behavior (I'm sure of that). What you described is item stacks being modified in client but not server, causing data to be inconsistent. But the code in `v3.2.1` communicates to the integrated server before each swap, so data inconsistency won't happen. In my tests, integrated servers (single player worlds) worked well, as long as LAN world hosts, but remote servers (multiplayer world joiners) are simply unable to swap their slots at all. So please always be up-to-date!

2. **The buggy code cannot communicate with remote server.**

As I mentioned, because **Tap Tab** doesn't provide a server side mod since 1.x, it is unable to communicate with remote servers directly, and I haven't realized that until now. In the latest version `v3.2.2`, it invokes the methods provided by interaction managers so is able to communicate with all kinds of servers indirectly. It works well to me.

Remember to update to [`v3.2.2`]() and report if any further bug appears.
