### ISSUE TITLE
This mod is incompatible with item sorting mods

### ISSUE THREAD

**Issue by WerySkok** [KrLite/Tap-Tab#7]
I tried Inventory Profiles Next and Mouse Wheelie mods, neither of them don't work with this mod and the game crashes when joining the world.

**Comment by KrLite** [comment]
Could you please provide your Minecraft version and a crash log or so?

**Comment by KrLite** [comment]
Here are my test results on `1.20.1`:

- **Inventory Profiles Next:** No crashes, but item on main hand **will not be swapped if `Auto Refill` is enabled.** No malignant bugs found.
- **Mouse Wheelie:** Almost the same as above, no crashes, item on main hand **will not be swapped if `Auto Refill` is enabled.**

**Comment by KrLite** [comment]
Hi there, I've seen your messages on Discord. Well, it may neither be a bug of **Tap Tab** nor a bug of **IPN** or so... It may be a bug of the quilt loom and its mixin remapper. If you load only **Tap Tab** and **IPN** on an isolated `Fabric 1.18.2` you will find **Tap Tab** is not working at all, but not causing crashes. On the other hand, the modpack **Cabricality** is running on `Quilt 1.18.2` within it's highly customized core mod, which bring us a huge uncertainty.
The crash(with the log `mixin apply failed...`) somehow happened to other mods before, which turned out to be a misuse of quilt loom version.
In brief, **Tap Tab** is not causing the crash, and this is not a fixable bug.

Anyway, thank you for reporting!
